spring:
  profiles:
    include: aifeedback
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: none          # 스키마는 Flyway가 담당
    properties:
      hibernate:
        auto_quote_keyword: true