spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/planus
    username: planus
    password: planus
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
