-- =====================================================================
-- V2__aifeedback_schema.sql  (Postgres + pgvector)  — 이슈 #1 AI-01 변경
-- V1(기준 스키마) 위에 적용.
-- =====================================================================

-- pgvector 확장 (memo_embedding 벡터 검색용)
CREATE EXTENSION IF NOT EXISTS vector;

-- [1] expense: 감정·예정·고정 (RAG·[6] 예측 의존)
ALTER TABLE expense
    ADD COLUMN emotion      VARCHAR(20),     -- NECESSARY/SATISFIED/IMPULSE/STRESS_RELIEF/REGRET (앱 enum)
  ADD COLUMN is_planned   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN is_recurring BOOLEAN NOT NULL DEFAULT FALSE;

-- [2] ai_feedbacks: 주/월 구분 + [7] 연결 컬럼, confidence → 밴드
ALTER TABLE ai_feedbacks
    ADD COLUMN period_type  VARCHAR(10) NOT NULL DEFAULT 'WEEKLY',
  ADD COLUMN period_start DATE,
  ADD COLUMN period_end   DATE,
  ADD COLUMN category_id  BIGINT,
  ADD COLUMN advice_type  VARCHAR(50);
-- 기존 confidence(DOUBLE) 폐기 → 규칙 밴드 VARCHAR (신규 DB, 데이터 없음)
ALTER TABLE ai_feedbacks DROP COLUMN confidence;
ALTER TABLE ai_feedbacks ADD COLUMN confidence VARCHAR(10);  -- HIGH/MEDIUM/LOW

-- [3] user_reactions: 거부사유 + 권고 카테고리
--   reaction 은 V1에서 VARCHAR(50)로 변환됨(앱이 HELPFUL/NOT_HELPFUL 사용)
ALTER TABLE user_reactions
    ADD COLUMN rejection_reason VARCHAR(20),  -- NOT_MY_SITUATION/ALREADY_KNOWN/DONT_WANT_REDUCE/TOO_REPETITIVE/OTHER
  ADD COLUMN category_id      BIGINT;

-- [4] category 11종 시드
INSERT INTO category (id, name) VALUES
                                    (1,'식료품'), (2,'주류·담배'), (3,'의류·신발'), (4,'가정용품·가사'),
                                    (5,'보건'),   (6,'교통'),     (7,'정보통신'),  (8,'오락·문화'),
                                    (9,'교육'),   (10,'외식·숙박'),(11,'기타')
    ON CONFLICT (id) DO NOTHING;

-- [5] memo_embedding: pgvector 벡터 저장 + HNSW 코사인 인덱스 (DATA-02: 벡터+참조만)
CREATE TABLE IF NOT EXISTS memo_embedding (
                                              id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              expense_id  BIGINT NOT NULL UNIQUE REFERENCES expense(id),
    user_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    emotion     VARCHAR(20),
    embedding   vector(2000) NOT NULL,
    ref_date    DATE NOT NULL,
    is_embedded BOOLEAN NOT NULL DEFAULT TRUE
    );
CREATE INDEX IF NOT EXISTS idx_memo_emb_user_date ON memo_embedding (user_id, ref_date);
-- 코사인 거리 연산자(<=>) 용 HNSW 인덱스
CREATE INDEX IF NOT EXISTS idx_memo_emb_hnsw
    ON memo_embedding USING hnsw (embedding vector_cosine_ops);

-- =====================================================================
-- 검증:
--   SELECT extname FROM pg_extension WHERE extname='vector';
--   \d expense   /  \d ai_feedbacks  /  \d user_reactions  /  \d memo_embedding
--   SELECT count(*) FROM category;   -- 11
-- =====================================================================