-- =====================================================================
-- V4__pipeline_v2_refactor.sql
-- RAG(memo_embedding + pgvector) 제거, 결정론적 파이프라인 v2 스키마 추가.
-- =====================================================================

-- memo_embedding 테이블 + 인덱스 삭제
DROP INDEX IF EXISTS idx_memo_emb_hnsw;
DROP INDEX IF EXISTS idx_memo_emb_user_date;
DROP TABLE IF EXISTS memo_embedding;

-- pgvector 확장 제거 (memo_embedding이 유일한 사용처)
DROP EXTENSION IF EXISTS vector;

-- budget_snapshot (버전 관리 예산)
CREATE TABLE budget_snapshot (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES "user"(id),
    year_month   DATE NOT NULL,
    version      INT NOT NULL DEFAULT 1,
    total_budget BIGINT NOT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_budget_snapshot_ver ON budget_snapshot(user_id, year_month, version);

CREATE TABLE budget_snapshot_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES budget_snapshot(id),
    category_id BIGINT NOT NULL REFERENCES category(id),
    amount      BIGINT NOT NULL
);

-- user_profile (누적 해석 데이터)
CREATE TABLE user_profile (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL UNIQUE REFERENCES "user"(id),
    repeat_patterns  JSONB NOT NULL DEFAULT '{}',
    sensitive_areas  JSONB NOT NULL DEFAULT '[]',
    compliance_rate  DOUBLE PRECISION DEFAULT 0.0,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- memo_question_queue ([3.5] 지연 질문)
CREATE TABLE memo_question_queue (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES "user"(id),
    expense_id         BIGINT NOT NULL REFERENCES expense(id),
    category_id        BIGINT NOT NULL REFERENCES category(id),
    anomaly_magnitude  DOUBLE PRECISION NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    question_week      DATE NOT NULL,
    answered_at        TIMESTAMP,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_mqq_user_status ON memo_question_queue(user_id, status);

-- ai_feedbacks 확장 (파이프라인 v2 필드)
ALTER TABLE ai_feedbacks
    ADD COLUMN IF NOT EXISTS feedback_type  VARCHAR(20),
    ADD COLUMN IF NOT EXISTS payload        JSONB,
    ADD COLUMN IF NOT EXISTS prompt_version VARCHAR(20),
    ADD COLUMN IF NOT EXISTS logic_version  VARCHAR(20);

-- month_end_verification (월말 검증)
CREATE TABLE month_end_verification (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL REFERENCES "user"(id),
    year_month             DATE NOT NULL,
    predicted_total        BIGINT NOT NULL,
    actual_total           BIGINT NOT NULL,
    mape                   DOUBLE PRECISION NOT NULL,
    post_suggestion_change JSONB,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uk_mev_user_month ON month_end_verification(user_id, year_month);
